version: "2"

services:
  zk:
    image: garland/zookeeper
    network_mode: host
    ports:
     - "2181:2181"
     - "2888:2888"
     - "3888:3888"

  master:
    image: mesosphere/mesos-master:0.28.0-2.0.16.ubuntu1404
    network_mode: host
    environment:
      MESOS_ZK: zk://127.0.0.1:2181/mesos
      MESOS_QUORUM: 1
      MESOS_CLUSTER: docker-compose
      MESOS_REGISTRY: replicated_log
    ports:
     - "5050:5050"
    depends_on:
      - zk

  slave:
    image: mesosphere/mesos-slave:0.28.0-2.0.16.ubuntu1404
    network_mode: host
    pid: host
    environment:
      MESOS_MASTER: zk://127.0.0.1:2181/mesos
      MESOS_CONTAINERIZERS: docker,mesos
      MESOS_PORT: 5051
      MESOS_RESOURCES: ports(*):[11000-11999]
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /usr/local/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zk

  marathon:
    image: mesosphere/marathon:v1.0.0-RC1
    network_mode: host
    environment:
      MARATHON_MASTER: zk://127.0.0.1:2181/mesos
    ports:
     - "8080:8080"
    depends_on:
      - zk
